[project]
name = 'Claritygov'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Claritygov]
path = 'contracts/Claritygov.clar'
clarity_version = 3
epoch = 3.1

[contracts.proposal-timeline]
path = 'contracts/proposal-timeline.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
